# Generated by Django 5.0.7 on 2024-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_service", models.CharField(max_length=50)),
                ("username_service", models.CharField(max_length=50)),
                ("password_service", models.CharField(max_length=50)),
            ],
        ),
    ]
